---
- name: WSL Configuration Playbook
  hosts: wsl_installations
  become: true
  gather_facts: true

  pre_tasks:
    - name: "Check for empty variables"
      assert:
        that:
          - first_name        | default("") | trim != ""
          - last_name         | default("") | trim != ""
          - lnx_user          | default("") | trim != ""
          - win_user          | default("") | trim != ""
          - wsl_hostname      | default("") | trim != ""
          - ansible_sudo_pass | default("") | trim != ""
          - system_users      | default("") | trim != ""
        msg: "All required variables must have a value"
        quiet: true
      tags: always

    - name: "Update package cache"
      package: update_cache=yes cache_valid_time=604800
      tags: always

  roles:
    # Windows integration
    - role: wsl-win-integration
      wsl_config_users: "{{ system_users }}"
      wsl_config_wsl_hostname: "{{ wsl_hostname }}"

    # System tools
    - role: openssh
      ssh_agent_enabled: "{{ not wsl_keeagent_enabled | default(False) | bool }}"
    - role: bash
      bash_users: "{{ system_users }}"
    - role: vim
      airline_theme: "{{ vim_airline_theme | default(omit) }}"
      color: "{{ vim_theme | default(omit) }}"
      tags: vim

    # Keys and certificates
    - role: ssl-certs
    - role: ssh-keys
      ssh_user_keys: "{{ system_users }}"
      when: not wsl_keeagent_enabled | default(False) | bool
    - role: wsl-keeagent
      when: wsl_keeagent_enabled | default(False) | bool
    - role: gpg-keys

    # Tooling
    - role: git
      git_users: "{{ system_users }}"
    - role: java
    - role: scala
    - role: docker
      tags: docker

    # Customizations
    - role: starship
      starship_users: "{{ system_users }}"

  post_tasks:
    - name: "Apt cleanups"
      apt: update_cache=false autoclean=true autoremove=true
      changed_when: false
      tags: always
