---
# Ansible Galaxy Collections
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

# Ansible Galaxy Roles
roles:
  - name: wsl-win-integration
    src: https://github.com/ColOfAbRiX/role-wsl-config.git
    scm: git

  - name: ssl-certs
    src: https://github.com/ColOfAbRiX/role-ssl-certs.git
    scm: git

  - name: openssh
    src: https://github.com/ColOfAbRiX/role-openssh.git
    scm: git

  - name: ssh-keys
    src: https://github.com/ColOfAbRiX/role-ssh-keys.git
    scm: git

  - name: wsl-keeagent
    src: https://github.com/ColOfAbRiX/role-wsl-keeagent.git
    scm: git

  - name: bash
    src: https://github.com/ColOfAbRiX/role-bash.git
    scm: git

  - name: starship
    src: https://github.com/rolehippie/starship.git
    scm: git

  - name: git
    src: https://github.com/ColOfAbRiX/role-git.git
    scm: git

  - name: java
    src: https://github.com/geerlingguy/ansible-role-java.git
    scm: git

  - name: sbt
    src: https://github.com/ColOfAbRiX/role-sbt.git
    scm: git

  - name: scala
    src: https://github.com/ColOfAbRiX/role-scala.git
    scm: git

  - name: docker
    src: https://github.com/geerlingguy/ansible-role-docker.git
    scm: git

  - name: vim
    src: https://github.com/tonipamies/ansible-role-vim.git
    scm: git
