---
galaxy_info:
  role_name: wsl_environment
  author: Fabrizio
  description: Configure WSL-specific environment settings and fixes
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - wsl
    - wsl2
    - environment
    - gpg

dependencies: []
