---
# Main user starship config definition
main_user_starship: {}

# Support for drop-in aliases plus several default ones
bash_features_aliases:
  name:  aliases
  state: present
  files: []

# Support for drop-in autocomplete plus several useful ones
bash_features_autocomplete:
  name:  autocomplete
  state: present

# Advanced message-of-the-day
bash_features_motd:
  name:  motd
  state: present

# Custom bash history settings
bash_features_history:
  name:  history
  state: present

# # Custom shell prompt
# bash_features_prompt:
#   name:  prompt
#   state: present


# Aggregating all the above features
bash_features:
 - "{{ bash_features_autocomplete   | default({'name': 'autocomplete'}) }}"
 - "{{ bash_features_motd           | default({'name': 'motd'}) }}"
 - "{{ bash_features_history        | default({'name': 'history'}) }}"
 - "{{ bash_features_aliases        | default({'name': 'aliases'}) }}"
 - "{{ bash_features_history2syslog | default({'name': 'history2syslog'}) }}"
 - "{{ bash_features_prompt         | default({'name': 'prompt'}) }}"
