---

# Where to place SSH keys in this repository
ssh_keys_base: data/ssh_keys

# Where to place SSL certificates in this repository
ssl_store_path: data/ssl_certificates

# Some Windows path shortcuts
windows_root: "/mnt/c/Users"
windows_user_root: "{{ windows_root }}/{{ win_user }}"
windows_user_appdata: "{{ windows_user_root }}/AppData"

# For stronger SSH key format
ssh_identity_files:
 - ~/.ssh/id_ed25519
