ANSIBLE_CORE_VERSION="2.17.14"
ANSIBLE_VERSION="10.7.0"
ANSIBLE_REPO_PATH=/var/tmp/ansible-wsl
VAULT_FILE=vault.txt
LNX_SECRETS_YML=host_vars/linux/secrets.yml
WIN_SECRETS_YML=host_vars/windows/secrets.yml
GPG_KEY_PATH="data/gpg_keys"
SSH_KEY_PATH="data/ssh_keys"
SSL_CERTS_PATH="data/ssl_certs"
